name: Development Build (Galaxy A50)

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'wip-*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Build KSU'
        required: false    

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"

    - name: Update Debian/Ubuntu Repositories
      run: sudo apt-get update

    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          ./build.sh --magisk --automated --device a50 --variant oneui --android 12 --dirty

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname Mint*-*.zip` ./release/
          cp .config ./release/kernel_config_a50_oneui-s-e.txt

    - name: Upload kernel image artifact
      uses: actions/upload-artifact@v2
      with:
        name: Kernel Image
        path: 'tools/make/boot.img'
        if-no-files-found: error

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: Kernel Config
        path: 'release/kernel_config_a50_oneui-s-e.txt'
        if-no-files-found: error

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: 'release'
        if-no-files-found: error
